"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var chien_js_1 = require("./chien.js");
var chat_js_1 = require("./chat.js");
var oiseau_js_1 = require("./oiseau.js");
var zoo_js_1 = require("./zoo.js");
var animal_js_1 = require("./animal.js");
var zoo = new zoo_js_1.default();
var monChien = new chien_js_1.default("Buddy", "Chien", 5);
var monChat = new chat_js_1.default("Whiskers", "noir", "Chat", 7);
var monOiseau = new oiseau_js_1.default("Tweetie", "Oiseau", 2);
var listAnimal = [monChat, monChien, monOiseau];
monChat.manger();
monChien.manger();
monChat.mouvement();
monOiseau.mouvement();
zoo.ajouterAnimal(monChien);
zoo.ajouterAnimal(monChat);
zoo.ajouterAnimal(monOiseau);
zoo.afficherAnimaux();
var ageMoy = animal_js_1.default.calculerAgeMoyen(listAnimal);
console.log("l'age moyen est ".concat(ageMoy));
